### ISSUE TITLE
Merge with webpush-java

### ISSUE THREAD

**Issue by gauntface** [gauntface/web-push-java#4]
Hi @ameyakarve,

At the moment we have two Java clients for web-push and it's caused some confusion for developers in terms of which one to use.

Looking at the two repo's in terms of commits, https://github.com/web-push-libs/webpush-java seems to be more actively maintained. Is there anything this repo does that the other one doesn't? If so would you be willing to work with the author of webpush-java to get them landed and ultimately merge this repo with that one?

cc @marco-c @MartijnDwars for thoughts on this.

Kind Regards,
Matt

**Comment by martijndwars** [comment]
I don't see anything in web-push-java that's not covered by webpush-java, but I'm happy to help out if needed.

**Comment by marco-c** [comment]
@gauntface I think we should do this now. If there are things @ameyakarve wants to integrate in webpush-java, he can do it later on.

How should we handle the merge?

**Comment by ameyakarve** [comment]
Saw this only now. I was just about to push out VAPID changes to mine, but I'll be happy to merge, as the functionality remains the same :)

**Comment by marco-c** [comment]
Sounds great! How should we handle the merge? Is there a way to make this repo automatically redirect to the other one? Or should we just add a README pointing to the other repo?

**Comment by gauntface** [comment]
Would be good to get any code changes made and transfer this repo back to @ameyakarve and add a deprecation notice pointing to the web-push one (Only reason for the transfer is that I've seen some people get confused that this org has two Java clients if they are new to the org).

**Comment by martijndwars** [comment]
Green light from my side.

**Comment by ameyakarve** [comment]
Is there a clean way to transfer on GitHub that you guys know of, or should I just fork and then close this one?

**Comment by gauntface** [comment]
You should be able to transfer under settings.
![screenshot from 2017-08-28 12 58 36](https://user-images.githubusercontent.com/139760/29791094-a3942218-8bf0-11e7-8e3c-1983cd473513.png)

**Comment by martijndwars** [comment]
FYI: I cannot access the settings of https://github.com/web-push-libs/webpush-java, so unless you've changed something for @ameyakarve I assume he won't be able to access the settings of https://github.com/web-push-libs/web-push-java.

**Comment by gauntface** [comment]
I transferred to myself and now transferring to @ameyakarve

**Comment by marco-c** [comment]
Any news?

**Comment by martijndwars** [comment]
`web-push-java` was moved out of the organization (it still lives under @gauntface now, https://github.com/gauntface/web-push-java) and `webpush-java` remains.

**Comment by marco-c** [comment]
Should we redirect from https://github.com/gauntface/web-push-java to webpush-java? Or add a comment pointing to that repo.

**Comment by martijndwars** [comment]
`web-push-java` already says "I may not get too much time to actively maintain this. I can add ownership if anyone is interested", so we might as well point users towards `webpush-java` indeed.

**Comment by ameyakarve** [comment]
I have added a link in the readme. Sorry for the delay :-)

**Comment by marco-c** [comment]
Thanks!
